set -g mouse off
set -g status on
set -g status-style fg=white,bg=white
set -g pane-border-style fg=blue

set -g history-limit 100000
set -g automatic-rename off
bind-key -n C-F send-prefix

set -g default-shell /bin/zsh
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*:Tc"
set -g status-style fg=colour39,bg=colour235
set -g status-left "#[fg=colour234,bg=colour82,bold] #S #[fg=colour82,bg=colour39]#[fg=colour234,bg=colour39] #H #[fg=colour39,bg=colour234]"
set -g status-right "#[fg=colour39,bg=colour234]#[fg=colour234,bg=colour39] %H:%M #[fg=colour82,bg=colour39]#[fg=colour234,bg=colour82] #(whoami) "
# Window styling with separators
set -g window-status-format "#[fg=colour244] #I:#W "
set -g window-status-current-format "#[fg=colour82,bold] #I:#W "

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
